# Generated by Django 5.2 on 2025-08-02 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0003_pet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes for review'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_user_submitted',
            field=models.BooleanField(default=False, help_text='Submitted by user (not admin)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('available', 'Available'), ('pending', 'Pending Sale'), ('sold', 'Sold/Adopted'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
    ]
