# Generated by Django 5.2 on 2025-08-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0004_pet_admin_notes_pet_is_user_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsePet',
            fields=[
            ],
            options={
                'verbose_name': 'Browse Pet (Admin Added)',
                'verbose_name_plural': 'Browse Pets (Admin Added)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('petpalapp.pet',),
        ),
        migrations.CreateModel(
            name='MarketplacePet',
            fields=[
            ],
            options={
                'verbose_name': 'Marketplace Pet (User Submitted)',
                'verbose_name_plural': 'Marketplace Pets (User Submitted)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('petpalapp.pet',),
        ),
        migrations.AddField(
            model_name='pet',
            name='address',
            field=models.CharField(blank=True, help_text='Full address', max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=11, null=True),
        ),
    ]
