# Generated by Django 5.2 on 2025-09-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0005_browsepet_marketplacepet_pet_address_pet_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='longitude',
        ),
    ]
