# Generated by Django 5.2 on 2025-09-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0007_remove_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='address',
            field=models.CharField(blank=True, help_text='Full address from map selection', max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=11, null=True),
        ),
    ]
