# Generated by Django 5.2 on 2025-10-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0008_pet_address_pet_latitude_pet_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedPet',
            fields=[
            ],
            options={
                'verbose_name': 'Marketplace - Approved',
                'verbose_name_plural': 'Marketplace → ✅ Approved Pets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('petpalapp.pet',),
        ),
        migrations.CreateModel(
            name='PendingPet',
            fields=[
            ],
            options={
                'verbose_name': 'Marketplace - Pending Review',
                'verbose_name_plural': 'Marketplace → 📋 Pending Review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('petpalapp.pet',),
        ),
        migrations.CreateModel(
            name='RejectedPet',
            fields=[
            ],
            options={
                'verbose_name': 'Marketplace - Rejected',
                'verbose_name_plural': 'Marketplace → ❌ Rejected Pets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('petpalapp.pet',),
        ),
        migrations.AddField(
            model_name='accessory',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
    ]
