# Generated by Django 5.2 on 2025-11-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0013_listingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingpayment',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='listingpayment',
            name='pet',
        ),
        migrations.AddField(
            model_name='listingpayment',
            name='submissions_used',
            field=models.IntegerField(default=0, help_text='Number of pet submissions already made'),
        ),
        migrations.AddField(
            model_name='listingpayment',
            name='total_submissions_allowed',
            field=models.IntegerField(default=5, help_text='Number of pets that can be submitted with this payment'),
        ),
    ]
