# Generated by Django 5.2 on 2025-11-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0015_featurecard_herosection_homepagesettings_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of items in stock'),
        ),
    ]
