# Generated by Django 5.2 on 2025-11-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0017_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_urgent',
        ),
    ]
