# Generated by Django 5.2 on 2025-11-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0018_remove_pet_is_featured_remove_pet_is_urgent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='source',
            field=models.CharField(choices=[('browse_pets', 'Browse Pets'), ('marketplace', 'Marketplace')], default='browse_pets', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'breed', 'source')},
        ),
    ]
