# Generated by Django 5.2 on 2025-11-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0020_chatthread_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
