# Generated by Django 5.2 on 2025-11-29 09:16

from django.db import migrations


def populate_pet_field(apps, schema_editor):
    """Populate pet field for existing wishlist items based on their breed"""
    WishlistItem = apps.get_model('petpalapp', 'WishlistItem')
    Pet = apps.get_model('petpalapp', 'Pet')
    
    for item in WishlistItem.objects.filter(pet__isnull=True):
        # Try to find a pet with the same breed
        pet = Pet.objects.filter(breed=item.breed, status='available').first()
        if pet:
            # Check if this wishlist-pet combination already exists
            existing = WishlistItem.objects.filter(wishlist=item.wishlist, pet=pet).exclude(id=item.id).exists()
            if existing:
                # Delete this duplicate item
                item.delete()
            else:
                item.pet = pet
                item.save()
        else:
            # If no pet found, delete the orphaned wishlist item
            item.delete()


def reverse_populate(apps, schema_editor):
    """Reverse operation - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0022_alter_wishlistitem_unique_together_wishlistitem_pet_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_pet_field, reverse_populate),
    ]
