# Generated by Django 5.2 on 2025-11-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0023_auto_20251129_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='health_certificate_file',
            field=models.FileField(blank=True, help_text='Upload health certificate (PDF/Image)', null=True, upload_to='health_certificates/'),
        ),
    ]
