# Generated by Django 5.2 on 2025-11-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0024_pet_health_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='behavior_traits',
            field=models.TextField(blank=True, default='', help_text='Notable behavioral characteristics'),
        ),
        migrations.AddField(
            model_name='breed',
            name='breed_history',
            field=models.TextField(blank=True, default='', help_text='Historical background and development of the breed'),
        ),
        migrations.AddField(
            model_name='breed',
            name='climate_tolerance',
            field=models.CharField(blank=True, default='', help_text='Climate preferences (e.g., Cold tolerant, Heat sensitive)', max_length=100),
        ),
        migrations.AddField(
            model_name='breed',
            name='coat_type',
            field=models.CharField(blank=True, default='', help_text='Type of coat (e.g., Double coat, Wire-haired, Curly)', max_length=100),
        ),
        migrations.AddField(
            model_name='breed',
            name='common_health_issues',
            field=models.TextField(blank=True, default='', help_text='Common health problems for this breed (one per line)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='diet_recommendations',
            field=models.TextField(blank=True, default='', help_text='Specific dietary needs and recommendations'),
        ),
        migrations.AddField(
            model_name='breed',
            name='exercise_details',
            field=models.TextField(blank=True, default='', help_text='Specific exercise needs and activity recommendations'),
        ),
        migrations.AddField(
            model_name='breed',
            name='feeding_notes',
            field=models.TextField(blank=True, default='', help_text='Special feeding considerations or restrictions'),
        ),
        migrations.AddField(
            model_name='breed',
            name='first_time_owner_friendly',
            field=models.BooleanField(default=True, help_text='Suitable for first-time dog owners'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fun_fact_1',
            field=models.TextField(blank=True, default='', help_text='Interesting fact about origin/history'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fun_fact_2',
            field=models.TextField(blank=True, default='', help_text='Interesting fact about intelligence'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fun_fact_3',
            field=models.TextField(blank=True, default='', help_text='Interesting fact about special talents'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fun_fact_4',
            field=models.TextField(blank=True, default='', help_text='Interesting fact about popularity'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fun_fact_5',
            field=models.TextField(blank=True, default='', help_text='Interesting fact about unique traits'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fun_fact_6',
            field=models.TextField(blank=True, default='', help_text='Interesting fact about ideal owners'),
        ),
        migrations.AddField(
            model_name='breed',
            name='genetic_conditions',
            field=models.TextField(blank=True, default='', help_text='Known genetic conditions to be aware of'),
        ),
        migrations.AddField(
            model_name='breed',
            name='good_with_cats',
            field=models.BooleanField(default=False, help_text='Generally good with cats'),
        ),
        migrations.AddField(
            model_name='breed',
            name='good_with_other_dogs',
            field=models.BooleanField(default=True, help_text='Generally good with other dogs'),
        ),
        migrations.AddField(
            model_name='breed',
            name='good_with_strangers',
            field=models.BooleanField(default=True, help_text='Generally friendly with strangers'),
        ),
        migrations.AddField(
            model_name='breed',
            name='grooming_details',
            field=models.TextField(blank=True, default='', help_text='Detailed grooming requirements and schedule'),
        ),
        migrations.AddField(
            model_name='breed',
            name='health_screening',
            field=models.TextField(blank=True, default='', help_text='Recommended health tests and screenings'),
        ),
        migrations.AddField(
            model_name='breed',
            name='ideal_home',
            field=models.TextField(blank=True, default='', help_text='Ideal living environment (apartment, house with yard, etc.)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='mental_stimulation',
            field=models.TextField(blank=True, default='', help_text='Mental exercise and enrichment needs'),
        ),
        migrations.AddField(
            model_name='breed',
            name='origin_country',
            field=models.CharField(blank=True, default='', help_text='Country or region of origin', max_length=100),
        ),
        migrations.AddField(
            model_name='breed',
            name='original_purpose',
            field=models.CharField(blank=True, default='', help_text='Original breeding purpose (e.g., Herding, Hunting, Companion)', max_length=200),
        ),
        migrations.AddField(
            model_name='breed',
            name='shedding_level',
            field=models.CharField(blank=True, default='', help_text='Low, Moderate, or High', max_length=20),
        ),
        migrations.AddField(
            model_name='breed',
            name='socialization_needs',
            field=models.TextField(blank=True, default='', help_text='Socialization requirements and recommendations'),
        ),
        migrations.AddField(
            model_name='breed',
            name='special_considerations',
            field=models.TextField(blank=True, default='', help_text='Any special care or ownership considerations'),
        ),
        migrations.AddField(
            model_name='breed',
            name='temperament_description',
            field=models.TextField(blank=True, default='', help_text='Detailed personality and temperament description'),
        ),
        migrations.AddField(
            model_name='breed',
            name='training_tips',
            field=models.TextField(blank=True, default='', help_text='Breed-specific training advice and methods'),
        ),
    ]
