# Generated by Django 5.2 on 2025-11-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0024_pet_health_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender_availability',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], help_text='Gender availability: Male, Female, or Both', max_length=10, null=True),
        ),
    ]
