# Generated by Django 5.2 on 2025-11-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0025_breed_behavior_traits_breed_breed_history_and_more'),
        ('petpalapp', '0025_pet_gender_availability'),
    ]

    operations = [
    ]
