# Generated by Django 5.2 on 2025-12-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0026_merge_20251130_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='climate_tolerance',
            field=models.CharField(blank=True, default='', help_text='Climate preferences (e.g., Cold tolerant, Heat sensitive)', max_length=250),
        ),
    ]
