# Generated by Django 5.2 on 2025-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0027_alter_breed_climate_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='exercise',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='grooming',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='height',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='shedding_level',
            field=models.CharField(blank=True, default='', help_text='Low, Moderate, or High', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='breed',
            name='weight',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
