# Generated by Django 5.2 on 2025-12-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0028_alter_breed_exercise_alter_breed_grooming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='coat_type',
            field=models.CharField(blank=True, default='', help_text='Type of coat (e.g., Double coat, Wire-haired, Curly)', max_length=150),
        ),
        migrations.AlterField(
            model_name='breed',
            name='shedding_level',
            field=models.CharField(blank=True, default='', help_text='Low, Moderate, or High', max_length=100),
        ),
    ]
