# Generated by Django 5.2 on 2025-12-04 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0031_adminsupportthread_adminsupportmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsupportthread',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='adminsupportthread',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminSupportMessage',
        ),
        migrations.DeleteModel(
            name='AdminSupportThread',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
    ]
