# Generated by Django 5.2 on 2025-12-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalapp', '0032_remove_adminsupportthread_pet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningReport',
            fields=[
            ],
            options={
                'verbose_name': 'Earning Report',
                'verbose_name_plural': 'Earning Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('petpalapp.pet',),
        ),
        migrations.AddField(
            model_name='listingpayment',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listingpayment',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
